### PR TITLE
Move pgsqlstore from main Grafeas project

### PR DESCRIPTION
**Pull request by judavi**
Move pgsqlstore.go to grafeas-pgsql. Related to https://github.com/grafeas/grafeas/issues/341

### CODE REVIEW

**Comment by judavi** [comment]
Hi @aysylu. Kindly advice is this is the change needed for https://github.com/grafeas/grafeas/issues/341 I'll be really happy to also open the PR to update the main project as well. Thanks!

**Comment by aysylu** [comment]
Hi @judavi, thank you for your contribution! Is there a follow-up PR planned to integrate this storage implementation into the Grafeas server and build the image?

**Comment by judavi** [comment]
@aysylu yes! but if my knowledge of Go is correct first I need this file here in this repo and then I can build. Please correct me if I'm wrong I'm still learning about the nuts and bolts of the packages in Go :)

**Comment by aysylu** [comment]
@judavi great! you're welcome to split this up into multiple PRs (like you're doing right now), or do the whole thing at once if you'd like, as you should be able to update and build in the same PR. Looking forward to the next PR! Merging this now. And yes please, the PR with updating the main project would be great. Perhaps we should first complete the migration here and then delete it in the main project?

**Comment by judavi** [comment]
@aysylu I think I introduced an error but I'm not sure how I can fix it. My idea comes because if I try to do 
```bash
[judavi@grafeas grafeas]$ go get github.com/grafeas/grafeas-pgsql/go/v1beta1/storage
# github.com/grafeas/grafeas/proto/v1beta1/project_go_proto
proto/v1beta1/project_go_proto/project.pb.gw.go:244:75: too many arguments in call to runtime.NewPattern
proto/v1beta1/project_go_proto/project.pb.gw.go:244:135: undefined: runtime.AssumeColonVerbOpt
proto/v1beta1/project_go_proto/project.pb.gw.go:246:72: too many arguments in call to runtime.NewPattern
proto/v1beta1/project_go_proto/project.pb.gw.go:246:158: undefined: runtime.AssumeColonVerbOpt
proto/v1beta1/project_go_proto/project.pb.gw.go:248:74: too many arguments in call to runtime.NewPattern
proto/v1beta1/project_go_proto/project.pb.gw.go:248:134: undefined: runtime.AssumeColonVerbOpt
proto/v1beta1/project_go_proto/project.pb.gw.go:250:75: too many arguments in call to runtime.NewPattern
proto/v1beta1/project_go_proto/project.pb.gw.go:250:161: undefined: runtime.AssumeColonVerbOpt
# github.com/grafeas/grafeas/proto/v1beta1/grafeas_go_proto
proto/v1beta1/grafeas_go_proto/grafeas.pb.gw.go:921:81: too many arguments in call to runtime.NewPattern
proto/v1beta1/grafeas_go_proto/grafeas.pb.gw.go:921:194: undefined: runtime.AssumeColonVerbOpt
proto/v1beta1/grafeas_go_proto/grafeas.pb.gw.go:923:83: too many arguments in call to runtime.NewPattern
proto/v1beta1/grafeas_go_proto/grafeas.pb.gw.go:923:192: undefined: runtime.AssumeColonVerbOpt
proto/v1beta1/grafeas_go_proto/grafeas.pb.gw.go:925:84: too many arguments in call to runtime.NewPattern
proto/v1beta1/grafeas_go_proto/grafeas.pb.gw.go:925:197: undefined: runtime.AssumeColonVerbOpt
proto/v1beta1/grafeas_go_proto/grafeas.pb.gw.go:927:84: too many arguments in call to runtime.NewPattern
proto/v1beta1/grafeas_go_proto/grafeas.pb.gw.go:927:193: undefined: runtime.AssumeColonVerbOpt
proto/v1beta1/grafeas_go_proto/grafeas.pb.gw.go:929:90: too many arguments in call to runtime.NewPattern
proto/v1beta1/grafeas_go_proto/grafeas.pb.gw.go:929:210: undefined: runtime.AssumeColonVerbOpt
proto/v1beta1/grafeas_go_proto/grafeas.pb.gw.go:929:90: too many errors
```
What do you think?

**Comment by aysylu** [comment]
Could you please point me to the branch you're doing this work on? As is, you won't be able to use the storage code you copied yet.

**Comment by judavi** [comment]
Sure! https://github.com/judavi/grafeas/tree/grafeas-341

**Comment by judavi** [comment]
@aysylu you mean the repo on grafeas project right? https://github.com/judavi/grafeas/tree/grafeas-341

**Comment by aysylu** [comment]
@judavi: I mean the work you've been doing in this repo, `grafeas-pgsql` to link up the storage implementation to the grafeas server.

**Comment by judavi** [comment]
@aysylu got it! 🙈  https://github.com/judavi/grafeas-pgsql/tree/grafeas-341  https://github.com/judavi/grafeas-pgsql/tree/grafeas-341

**Pull request merged**
